### ISSUE TITLE
Add list of notary annotations

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#172]
Notary adds several annotations. Would it help to have a single markdown file that lists the annotations, and defines the format?
For instance, we've followed a camelCase formatting of annotations. To avoid new annotations from diverging or new annotations that are duplicative of existing ones, should we document these?

**Comment by sajayantony** [comment]
I would recommend adding a section to this https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#storage with annotations. 

Also, it is currently a bit confusing since there are annotations in the Payload and annotations in the manifest 
https://github.com/notaryproject/notaryproject/blob/main/signature-envelope-jws.md#storage

For all purposes my understanding is that registries aren't expected to look at the payload as currently registries and clients only look at the manifest at the lowest level.

**Comment by yizha1** [comment]
per the discussion in the community meeting, and the annotation is now described in Notary Project spec https://github.com/notaryproject/specifications/blob/main/specs/signature-specification.md, we close this issue, and we can create a new issue to discuss any new annotations in the future.
