### ISSUE TITLE
Inconsistent Signing Workflow

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/specifications#189]
There is a conflict in the signing workflow.
- [signing-and-verification-workflow.md](https://github.com/notaryproject/notaryproject/blob/v1.0.0-draft.3/signing-and-verification-workflow.md#signing-steps) verifies the certificate chain **before** signing (steps _1.i_ and _1.iii_).
- [specs/plugin-extensibility.md](https://github.com/notaryproject/notaryproject/blob/v1.0.0-draft.3/specs/plugin-extensibility.md#signing-workflow-using-plugin) verifies the ceritifate chain **after** signing (steps _5.i.c_ and _5.i.d.c_).

**Comment by rgnote** [comment]
I think [signing-and-verification-workflow.md](https://github.com/notaryproject/notaryproject/blob/v1.0.0-draft.3/signing-and-verification-workflow.md#signing-steps) was written with local signing in mind and [specs/plugin-extensibility.md](https://github.com/notaryproject/notaryproject/blob/v1.0.0-draft.3/specs/plugin-extensibility.md#signing-workflow-using-plugin) was written for remote signing. Since we don't have access to the chain before we generate the digital signature in the case of remote signing, we need to verify the chain *after* signing.
