### ISSUE TITLE
Request Clarification on the Definition of the term `Artifact`

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/specifications#277]
During the discussion of https://github.com/notaryproject/notation/discussions/767, we found that it is not clear how the term `Artifact` is defined.

Currently, there are two interpretations of `Artifact`:
1. `Artifact = Blob Content + Media Type`: @shizhMSFT thinks artifacts of two types are different even if their blob contents are the same.  For example, a JSON file can be a valid SBOM file, a valid config, and a valid manifest at the same time. If this JSON file has 3 copies with different media types of SBOM, config, and manifest, they are 3 different artifacts.
2. `Artifact = Blob Content`: @priteshbandi thinks artifacts are the same as long as their blob contents are the same. In the above JSON file example, they are the same artifacts instead of 3 different artifacts.

## Why is the definition of the term `Artifact` important?

It is because the goal of Notary Project and its implementation `notation` is to sign and verify `Artifact` securely.

Since `Blob Content` can be implied by blob digest with negligible security differences when a cryptographic hash is used, we need to define the core of `notation` whether it is to sign and verify `digest + mediaType` or `digest` only.

**Comment by rchincha** [comment]
Is this question in the context of the dist-spec 1.1.0-rc3?

**Comment by shizhMSFT** [comment]
> Is this question in the context of the dist-spec 1.1.0-rc3?

This issue is a general question regardless of `image-spec` or `distribution-spec`.

**Comment by toddysm** [comment]
I am with @shizhMSFT on this one. The omission of media type may expose the content to attacks similar to how files are exploited.

**Comment by SteveLasker** [comment]
How an artifact is constructed should be left to the artifact author. Whether an artifact uses one more more files, or one more more blobs is really an implementation detail. 
A container image is an artifact. It has many files within each blob (aka `layer`). It has many blobs, that help with file size and transmission optimizations. It has another "file" called a config object. The entire graph of objects is "an artifact".

A single file, like an SBOM can also be an artifact. 

When notation is asked to "sign an artifact", it's signing the contents of a manifest with an `artifactType` of x/y/z. If it uses a single blob, or multiple blobs, does it matter?

**Comment by gokarnm** [comment]
From the perspective of proving integrity and authenticity, we are not signing the artifact itself, but a representation (the payload to sign) that uniquely identifies the artifact. And that can vary based on the use case.

For OCI artifacts, because descriptors are the supported mechanism to uniquely reference artifacts, the payload that we sign contain a descriptor. With the descriptor we reliably get the digest, size and media type, as they are supported by OCI specs. 

For signing files on disk, we can get digest and size reliably but not media type. A straw man example would be if we wanted to sign web hosted content and the URL or some unique ID of the artifact was important to determine uniqueness, the digest and size along with URL/ID would be included in the payload to be signed.

We should not be limited by the payload we defined for OCI artifact signing use cases, we can extend from it or define new payloads as required.

**Comment by priteshbandi** [comment]
> The omission of media type may expose the content to attacks similar to how files are exploited.

How? Notation should not try to interpret/decode the content being singed because 1) notation is not meant to validate mediatype 2) it's not scalable, which means notation cannot perform validation on the type of content being signed/verified. Therefore for notation media-type is similar to any signed attribute which can be passed with [`notation sign/verify -m key=value`](https://github.com/notaryproject/notation/blob/main/specs/commandline/sign.md#outline) flag.
Its responsibility of system consuming the verified content to avoid vulnerability similar to [CVE-2021-41190](https://github.com/advisories/GHSA-mc8v-mgrf-8f4m).
